'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MemoryGameLeprechauns.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Dr__Dre____Still_D_R_E__faster() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Dr__Dre____Still_D_R_E__faster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Leprechaun_Song_Intro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Leprechaun_Song_Intro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Leprechaun_Song_Loop() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Leprechaun_Song_Loop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splashscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splashscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Easy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Easy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Easy_Clicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Easy_Clicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Exit_Clicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Exit_Clicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Exit_Clicked1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Exit_Clicked1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Hard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Hard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Hard_Clicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Hard_Clicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Medium_Clicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Medium_Clicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Menu_clicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Menu_clicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsButton_Menu_clicked_new1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsButton_Menu_clicked_new1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsCard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsCardSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsCardSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsSpeelveld() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsSpeelveld", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TheLeprechaunsStartScherm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TheLeprechaunsStartScherm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
